# Generated by Django 2.1.2 on 2018-12-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='carb',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='chol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fbr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='pro',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='salt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sfat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='sgr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='tfat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
