# Generated by Django 2.1.2 on 2018-12-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20181214_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='carb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='chol',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='fbr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='pro',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='salt',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sfat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='sgr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='tfat',
            field=models.FloatField(default=0),
        ),
    ]
